# Login screen (Slick Greeter) with the Sai look.
[Greeter]
background=/usr/share/backgrounds/sai/default.png
draw-user-backgrounds=false
theme-name=Cinnamon-Delight
icon-theme-name=Win11
cursor-theme-name=Bibata-Modern-Classic
font-name=Be Vietnam Pro 11
